SELECT BOOK_ID
     , AUTHOR_NAME
     , TO_CHAR(PUBLISHED_DATE, 'yyyy-MM-dd') as PUBLISHED_DATE
  FROM BOOK A, AUTHOR B
 WHERE A.AUTHOR_ID = B.AUTHOR_ID
   AND CATEGORY = '경제'
 ORDER BY PUBLISHED_DATE;