SELECT PRODUCT_ID, PRODUCT_NAME, SUM(SALES) TOTAL_SALES
  FROM (SELECT A.PRODUCT_ID, A.PRODUCT_NAME, B.PRODUCE_DATE, A.PRICE*B.AMOUNT SALES
          FROM FOOD_PRODUCT A, FOOD_ORDER B
         WHERE A.PRODUCT_ID = B.PRODUCT_ID
           AND TO_CHAR(B.PRODUCE_DATE, 'YYYYMM') = '202205')
 GROUP BY PRODUCT_ID, PRODUCT_NAME
 ORDER BY TOTAL_SALES DESC, PRODUCT_ID